### ISSUE TITLE
ux: generate helper or backend route to trigger action on specified app

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-js-api#39]
Currently we can only specify the process_id (and this going to disapear as an UID) to trigger a custom action.

e.g:

```javascript
km.actions.triggerAction('5a26ca0ff419704978defc63', {
    server_name: 'door-control',
    process_id: 3,
    action_name: 'open door'
}).then(rep => {
```

Would it be possible to set an application name instead?

**Comment by Unitech** [comment]
looking forward an update on this (+avoid the issue with the office door)

**Comment by Eywek** [comment]
https://github.com/keymetrics/pm2-io-agent/pull/114
