### ISSUE TITLE
When a refresh token expires, js-api fails to reauthentify the user

### ISSUE THREAD

**Issue by BenoitZugmeyer** [keymetrics/pm2-io-js-api#49]
Steps to reproduce:
* Log in to the app.pm2.io dashboard
* Go to a bucket, settings, remove all tokens
* Refresh the page

Expected: The page is redirected to the oauth login page

Currently: Infinite loading

Related issue: #29 PR #45 

The PR #45 adds a call to `this.oauth_flow.deleteTokens(this.km)`, but since the user is not authenticated anymore and this call needs authentication, this call [is queued by `network.js`](https://github.com/keymetrics/pm2-io-js-api/blob/50ee7be633b2fcce8dabcb447a239656dbe50bd4/src/network.js#L106), and the flow stops here.

**Comment by Eywek** [comment]
https://github.com/keymetrics/pm2-io-js-api/blob/master/src/network.js#L244
