### ISSUE TITLE
Easy access to distribution file

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-js-api#61]
Can we add the dist/ folder in this repo? Or put a link to retrieve it on the documentation?
Also the documentation is missing when we want to use the js-api in the browser (we do not mention that the globally accessible library is window.Keymetrics)

**Comment by BenoitZugmeyer** [comment]
You can use https://unpkg.com/@pm2/js-api@0.5/dist/keymetrics.es5.min.js for all development purposes.

**Comment by Unitech** [comment]
great, I've added to to the doc: https://github.com/keymetrics/pm2-io-js-api/pull/62
