### ISSUE TITLE
Document endpoints parameter

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-js-api#63]
- swagger?

**Comment by Unitech** [comment]
Looks like there is an integration of jsdoc and swagger-io: 
https://github.com/Surnet/swagger-jsdoc 

Demo:
https://petstore.swagger.io

I'm looking for the same ui, so users can try JS API and HTTP API easily.
They would require to be able to authenticate via Oauth to be able to hit the routes and see the result:
![image](https://user-images.githubusercontent.com/757747/56897118-ea93d280-6a8d-11e9-8aad-2a4d9f7d5bf0.png)

**Comment by Eywek** [comment]
http://docs.api.cloud.pm2.io/Auth.html#register

**Comment by Unitech** [comment]
Good to this that the jsdoc can be generated easily.

Now the requirement is:
- [ ] Swagger interface, so we can interact with each routes
- [ ] Authentification button to retrieve token to be able to interact with routes (with pm2-io-js-api) (refer to bellow message)

**Comment by Unitech** [comment]
re-up this is important,
being able to see the result of the api is a must have

**Comment by Unitech** [comment]
@f-hj any insights on this?

**Comment by Unitech** [comment]
If I can help you out on this task just let me know
