### ISSUE TITLE
axios upgrade to v0.21.1

### ISSUE THREAD

**Issue by LiChangyi** [keymetrics/pm2-io-js-api#73]
Currently, Axios has version 0.21.1, which fixes a vulnerability in SSRF.
You can check the CHANGELOG.md file here , https://github.com/axios/axios/blob/v0.21.1/CHANGELOG.md

**Comment by ffflorian** [comment]
Ping @Unitech

**Comment by jxbadam** [comment]
Should upgrade axios to 0.26.0 which fixes a security bug in follow-redirects @Unitech 👍

**Comment by Unitech** [comment]
https://github.com/keymetrics/pm2-io-js-api/blob/master/package.json#L37 
best
